### ISSUE TITLE
Draw 'ball-in-range' zone on feed. Make toggle-able in feed settings UI.

### ISSUE THREAD

**Issue by jsren** [jsren/sdp-vision#2]
>  i was thinking we could have a little area displayed on the vision feed for where the grab range is supposed to be - mostly for eyeball testing to see if it looks reasonable.

 @Ramsey144

**Comment by LinasKo** [comment]
Done. Calibrations of that reside at the top of robot_instance.py. Currently calibrated for robot of team 10. Works very reliably if the ball is not obstructed and colors are calibrated properly.
