### ISSUE TITLE
Why do colour calibrations keep changing?

### ISSUE THREAD

**Issue by relnaggar** [jsren/sdp-vision#6]

**Comment by jsren** [comment]
@Ramsey144, @A-W-Smith : Need details & steps to reproduce

**Comment by A-W-Smith** [comment]
Just wondering as when we were testing, it would suddenly not pick up yellow despite the yellow robots not moving and video calibrations not changing.

**Comment by jsren** [comment]
Possible duplicate of #5. #4 and/or #7 might provide a partial-if-not-complete solution to yellow-tracking being lost, as this often occurs because the boundaries of the pitch are being detected as yellow.
