### ISSUE TITLE
Select `OUR_ROBOT` and team/enemy colours before launching vision & on UI

### ISSUE THREAD

**Issue by relnaggar** [jsren/sdp-vision#9]
The issue of telling the vision launcher which robots to look for before calling wait_for_launch() returns - at the moment it waits until ‘OUR_ROBOT’ has been found, which is defined manually in the vision launcher file - it is not controllable from the UI / as arguments to the launcher.

**Comment by A-W-Smith** [comment]
Can do that now. Would be nice to also have it automatically set to track our robot. Remind me to change that one line in strategy
